### ISSUE TITLE
Missing package.json

### ISSUE THREAD

**Issue by bastientanesie** [vitalwheat/redditEventCalendarBot#1]
Hey there, Pr. Maevis on duty! 🤣 

In order for others to install or even use your project, you must add your `package.json` so we can install your project's dependancies.  
The `package-lock.json` file is already versionned (which is good!) but is not enough by itself to install dependancies.

In future updates you should always commit both files, as changes in your `package.json` will be reflected in your `package-lock.json` automatically by NPM.

**Comment by vitalwheat** [comment]
package.json added to dev branch
